### ISSUE TITLE
哥哥，能给个js源码吗

### ISSUE THREAD

**Issue by lupanlong** [zixiwangluo/wxdh#1]
跪谢了额

**Comment by lupanlong** [comment]
> 跪谢了额

我的V，alalal95

**Comment by zixiwangluo** [comment]
> 跪谢了额

emmm，js源码不是在 static/app/js 这里面吗？你这该不会是下载的时候没建立对目录吧？

**Comment by lupanlong** [comment]
> > 跪谢了额
> 
> emmm，js源码不是在 static/app/js 这里面吗？你这该不会是下载的时候没建立对目录吧？

那里的js 都是bundle后的,不是源代码额

**Comment by lupanlong** [comment]
您能给个没有处理过的js源码吗？🙏

**Comment by zixiwangluo** [comment]
> > > 跪谢了额
> > 
> > 
> > emmm，js源码不是在 static/app/js 这里面吗？你这该不会是下载的时候没建立对目录吧？
> 
> 那里的js 都是bundle后的,不是源代码额

那我也没有，我拿这个仓库做github page玩的，这源码我也是从别的资源网下载的。。。下载下来就这样了

**Comment by lupanlong** [comment]
> 


> > > 跪谢了额
> > 
> > 
> > emmm，js源码不是在 static/app/js 这里面吗？你这该不会是下载的时候没建立对目录吧？
> 

> 

那您能把

**Comment by lupanlong** [comment]
> 

那您能提供一下资源网地址吗，谢谢啦

**Comment by zixiwangluo** [comment]
> > 
> 
> 那您能提供一下资源网地址吗，谢谢啦

https://www.dkewl.com/code/detail2521.html
我从这里下的
他那网赚盘下载慢得很，我下了十几分钟才下载下来，但他也不是原创哦，我也不知道他从哪搬的

**Comment by lupanlong** [comment]
> 

好的 谢谢大哥

**Comment by zixiwangluo** [comment]
> > 
> 
> 好的 谢谢大哥

小事，这玩意我看能运行起来就没管了，虽然js被处理过了，但应该问题不大吧
